### ISSUE TITLE
第5章について

### ISSUE THREAD

**Issue by osamu2001** [kentaro/puppet-book-support#1]
第5章 nginxのmanifestを書く
において、本文とmanifestの不一致する部分を見つけました。
# port番号について

nginx.ppには

> $port = 80

と書いてありますが、本文は

> $port = 8000

であることを前提に書かれています。
本文にはポート8000前提の箇所が複数あるのでmanifestを80から8000に
かえれば矛盾がなくなります。
# $name = "Puppet"について

本文には

> $port = 8000や$name = "Puppet"という箇所は、

とありますが、nginx.ppには

> $target = "Puppet"

とあります。
どちらかに統一したほうがよいと思います。
# テンプレートからセミコロンが抜けている

my.conf
には

> server {
>   listen <%= port %>

とありますが、

> server {
>   listen <%= port %> ;

としないとエラーになります。

**Comment by kentaro** [comment]
レポートありがとうございます! 最新版では修正されましたので、ご確認ねがいます。
